<?php
$form = $this->form;
$form->get('name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter your name'
]);
$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter your email',
    'rows'=>6
]);
$form->get('phone')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter your phone'
]);
$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->prepare();

?>

<h1>Add New Post</h1>

<p>
    Please fill out the following form and click the <i>Create</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('phone')); ?>
            <?= $this->formElement($form->get('phone')); ?>
            <?= $this->formElementErrors($form->get('phone')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>