
<footer class="bg-footer">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6 col-lg-4 my-4">
                <p class="title-address mt-3">Trung Tâm 1</p>
                <a class="content-address font-text" href="#"><i class="fa fa-map-marker mr-2" aria-hidden="true"></i> Lầu 5 và 8, Tòa nhà Khang Thông - Số 67 Nguyễn Thị Minh Khai, Quận 1, Tp.HCM</a>
                <p class="phone-address font-text"><i class="fa fa-phone mr-2" aria-hidden="true"></i> Số điện thoại: <a class="font-text" href="tel:028 3926 0022">028 3926 0022</a></p>
            </div>
            <div class="col-12 col-md-6 order-md-2 order-lg-1 col-lg-4 mt-md-n5 mt-4 mt-lg-4 mb-4">
                <p class="title-address mt-3">Trung Tâm 2</p>
                <a class="content-address font-text" href="#"><i class="fa fa-map-marker mr-2" aria-hidden="true"></i> Lầu 3, Tòa nhà Soho.Biz (SCJ) - Số 38 Huỳnh Lan Khanh, Q. Tân Bình, Tp.HCM</a>
                <p class="phone-address font-text"><i class="fa fa-phone mr-2" aria-hidden="true"></i> Số điện thoại: <a class="font-text" href="tel:028 3926 0022">028 3926 0022</a></p>
            </div>
            <div class="col-12 col-md-6 order-md-1 col-lg-4 my-4 grid-address-c">
                <div class="mt-3">
                    <p class="title-address">Khám Phá</p>
                    <p class="font-text">Chọn Green Academy</p>
                    <p class="font-text">Khóa học IT</p>
                    <p class="font-text">Khóa học Thiết kế</p>
                    <p class="font-text">Khóa học Tiếng Hàn</p>
                </div>
                <div class="mt-3">
                    <p class="title-address">Xem thêm</p>
                    <p class="font-text">Sự kiện</p>
                    <p class="font-text">Chính sách riêng tư</p>
                    <p class="font-text">Blog</p>
                    <p class="font-text">Free test</p>
                    <p class="font-text">Tài liệu miễn phí</p>
                </div>
            </div>
        </div>
    </div>
</footer>