<head>
    <meta charset="utf-8">
    <?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel'  => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => '',
    ])
        ->prependStylesheet($this->basePath('css/index.css'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-grid.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-reboot.css'))
        ->prependStylesheet($this->basePath('css/fontawesome-free-web/css/all.css'))
        ->prependStylesheet($this->basePath('css/font-awesome/css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('css/slick/slick.css'))
        ->prependStylesheet($this->basePath('css/slick/slick-theme.css'))
        ->prependStylesheet($this->basePath('css/animate-master/animate.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->appendFile($this->basePath('js/jquery-3.1.0.min.js'))
        ->appendFile($this->basePath('js/slick/slick.js'))
        ->appendFile($this->basePath('js/lazyload/lazyload.min.js'))
        ->appendFile($this->basePath('js/popper.min.js'))
        ->appendFile($this->basePath('js/bootstrap.js'))
        ->appendFile($this->basePath('js/effectjs/carousel.js'))
        ->appendFile($this->basePath('js/effectjs/lazyloadimg.js'))

    ?>
</head>