<section>
    <nav class="menu-layout">
        <div class="logo-layout">
            <img src="<?= $this->basePath('img/image.png') ?>"/>
        </div>
        <div class="content-layout">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Về Green Academy <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Khóa học
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Free-test</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Sự kiện</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Thư viện
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
            </ul>
            <div>
                <a class="content-layout-advisory" href="#">Nhận tư vấn</a>
            </div>
        </div>
    </nav>
    <div class="pos-f-t">
        <div class="collapse" id="navbarToggleExternalContent">
            <div class="bg-white p-4">
                <div class="grid-child-menu">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link text-menu" href="#">Về Green Academy <span
                                        class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-menu" href="#" id="navbarDropdownMenuLink"
                               data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                Khóa học
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item text-menu" href="#">Action</a>
                                <a class="dropdown-item text-menu" href="#">Another action</a>
                                <a class="dropdown-item text-menu" href="#">Something else here</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-menu" href="#">Free-test</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-menu" href="#">Sự kiện</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-menu" href="#" id="navbarDropdownMenuLink"
                               data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                Thư viện
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item text-menu" href="#">Action</a>
                                <a class="dropdown-item text-menu" href="#">Another action</a>
                                <a class="dropdown-item text-menu" href="#">Something else here</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <nav class="navbar  navbar-light bg-white grid-menu">
            <button class="navbar-toggler border-0 no-outline" type="button" data-toggle="collapse"
                    data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon my-toggler"></span>
            </button>
            <div class="logo-layout">
                <img src="<?= $this->basePath('img/image.png') ?>"/>
            </div>
            <a class="consult w-res" href="#">Nhận tư vấn</a>
        </nav>
    </div>
</section>